### ISSUE TITLE
decodeLogs throws "cannot find inputs of undefined"

### ISSUE THREAD

**Issue by ajsantander** [zeppelinos/zos-lib#72]
It appears that decodeLogs.js is not properly dealing with the situation exposed below.
It attempts to read an object that does not exist.

CLI command executed:
```
[AppManager] 
Setting implementation of Basil in contract directory...
[AppManager]  Implementation set: 0x77092acc78ed6cc2439fdc6bdf07d51271d76028
[AppManager] 
Setting stdlib [object Object]...
[PackageFilesInterface] Successfully written package.zos.development.json
zos create-proxy Basil --init --params 0x65a59bb097403551a3bb6cb2bd987389f2872d40 --network development
Using network 'development'.

[AppManager] 
Creating Basil proxy: initialize, 0x65a59bb097403551a3bb6cb2bd987389f2872d40...
[AppManager]  TX receipt received: 0xb6049b7a15aad01486d59d5b53a7376dd80c62e810b5aeff547f80ef74678d64
```

Error thrown:
```
TypeError: Cannot read property 'inputs' of undefined
    at new SolidityEvent (/home/ajs/zos/lib/node_modules/web3/lib/web3/event.js:35:25)
    at logs.map.log (/home/ajs/zos/lib/lib/decodeLogs.js:7:19)
    at Array.map (<anonymous>)
    at decodeLogs (/home/ajs/zos/lib/lib/decodeLogs.js:4:15)
    at AppManagerWrapper.createProxy (/home/ajs/zos/cli/src/models/AppManager.js:98:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

`console.log(JSON.stringify(log, null, 2))` in decodeLogs.js, after line 4:
```
{
  "logIndex": 1,
  "transactionIndex": 0,
  "transactionHash": "0xb6049b7a15aad01486d59d5b53a7376dd80c62e810b5aeff547f80ef74678d64",
  "blockHash": "0x053e80721d45f5eb17e6b2382518e91ed7c0e13cf574652831e440775599d233",
  "blockNumber": 94,
  "address": "0x9c45ea32ca605d59bc82a966c73be2b29647fb53",
  "data": "0x0",
  "topics": [
    "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b",
    "0x00000000000000000000000077092acc78ed6cc2439fdc6bdf07d51271d76028"
  ],
  "type": "mined"
}
```

`console.log(JSON.stringify(contract.events, null, 2))`
```
{
  "0x00fffc2da0b561cae30d9826d37709e9421c4725faebc226cbbb7ef5fc5e7349": {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "proxy",
        "type": "address"
      }
    ],
    "name": "ProxyCreated",
    "type": "event"
  }
}
```

**Comment by frangio** [comment]
See https://github.com/zeppelinos/zos-lib/pull/73.

Any chance you could try running this with those changes to see if it is fixed?
